color:
  key:
    hue: 44
  1:
    hueOffset: -150
  2:
    hueOffset: 120
  saturation: 41
  lightness:
    lighter: 90
    light: 75
    mid: 62
    dark: 44
    darker: 15
  foreground: '#333'
  background: '#CCC'
font: Lato
font_display: Montserrat
font_code: monospace
header_height: 9em
fitz: .5em
col: 18em
