color:
  key:
    hue: 44
  1:
    hueOffset: 0
  2:
    hueOffset: 0
  saturation: 27
  lightness:
    lighter: 20
    light: 40
    mid: 51
    dark: 70
    darker: 90
  foreground: '#EEE'
  background: 'hsla(0, 0%, 0%, .5)'
font: Lato
font_display: Josefin+Sans
font_code: monospace
header_height: 9em
fitz: .5em
col: 18em
