color:
  key:
    hue: 44
  1:
    hueOffset: 0
  2:
    hueOffset: 0
  saturation: 27
  lightness:
    lighter: 90
    light: 75
    mid: 51
    dark: 23
    darker: 0
  foreground: '#333'
  background: '#F9F9F9'
font: Lato
font_display: Josefin+Sans
font_code: monospace
header_height: 9em
fitz: .5em
col: 18em
